### PR TITLE
Bugfix: Added consentValue as per docs

### PR DESCRIPTION
**Pull request by TomDo1234**
## What

Makes the consent field act like in the docs, consentValue and boolean. Furthermore it also fixes the previous issue where even unchecked required consents would trigger a successful form submission (This is done by using value instead of consentValue)

## Why

Because it is a hotfix that fixes the consent field so that it follows the intended behavior in docs
## How

Registering the consentValue type inside FormFieldsValuesInput
## Checklist:

- [X ] This PR is tested to the best of my abilities.
- [X ] This PR follows the WordPress Coding Standards. 
- [X ] This PR has proper inline documentation. 
- [ ] This PR has unit tests to verify the code works as intended.
- [ ] The changes in this PR have been noted in CHANGELOG.md

### CODE REVIEW

**Comment by TomDo1234** [comment]
The pullrequest was done by my work account, but yeah I fixed it.

**Comment by TomDo1234** [comment]
@justlevine 

What do you think? Took me 4 commits to realize I was doing everything wrong, then I reverted the previous 4 commits and then did a final 5th one which fixed it :)

**Comment by TomDo1234** [comment]
@justlevine 

It took me 6 commits to fix this issue, but 4 of them were just me making mistakes and the 5th and 6th fixed them, just go to Files Changed to get the summary.

**Comment by justlevine** [comment]
Hey @TomDo1234 , as I just wrote in https://github.com/harness-software/wp-graphql-gravity-forms/issues/322#issuecomment-1288021475, it's the documentation that incorrect, not the behavior. 

We moved away from the `consentValue` input pattern in `v0.10` in favor of using the generic `value` for a bunch of reasons, and although it's possible we may reintroduce a different generic `bool` type field value input in the future, unless there's a major change to how GF Core handles this field, we'll likely stick with current pattern until the GraphQL spec (and WPGraphqL) add support for [input unions](https://github.com/graphql/graphql-spec/pull/825).

PS: the code itself is great. My bad for missing that part of the docs when I was releasing 😳, and I hope this doesn't deter you from contributing in the future 🤞

**Pull request closed without merging**
