### PR TITLE
Check if FieldValue exists in $entry before trying to return it. 

### PR DESCRIPTION
**Pull request by justlevine**
Address #16 .

This PR implements checks whether the FieldValue exists in `$entry` before trying to return the value. Prevents all those unnecessary error_log warnings when you're doing mutations on a single field.

**Note**: I opted for using `array_key_exists( $field['id'], $entry )` over `isset( $entry[ $field['id'] )`, as I feel it is more robust. That said, I did not change the few `{fieldtype}Field.php` that already use `isset`. If the maintainers have a preference for one or the other, I'm happy to switch this pr to use `isset()` or update the other files to use `array_key_exists`.

I _had to_ change the preexisting SignatureFieldValue check. since `! $entry[ $field['id'] ]` isnt the same as either `array_key_exists` or `isset`.

### CODE REVIEW

**Comment by tinytoolbox** [comment]
I need clarification on this.

**Comment by kellenmace** [comment]
Hey @justlevine – I generally prefer to use `isset()` to ensure that an element in an array is both set, and has a non-null value, which is why this code was written this way, FYI.

I only use `array_key_exists()` if I need to check if an array element has been explicitly set to `null`, which I find that I rarely ever need to do.

Between the two of them, I would argue that `isset()` is more "robust", since it checks two things (whether it is set and non-null), whereas `array_key_exists()` only checks one thing (whether it is set).

For a line like this one:
```
'street'  => array_key_exists( $field['inputs'][0]['id'], $entry ) ? $entry[ $field['inputs'][0]['id'] ] : null,
```

I think `isset()` would work fine, and actually, since this project has a minimum PHP requirement of 7.4, we could leverage the null coalescing operator to make the check very succinct, like this:
```
'street'  => $entry[ $field['inputs'][0]['id'] ]  ?? null,
```

What do you think?

Nice job on adding in additional checks to address the "unnecessary error_log warnings" that you mentioned, and thanks for contributing to this project! 👍

**Comment by justlevine** [comment]
@kellenmace thanks for the clarification!

My only concern is that if something in the `$field` array doesn't exist, then `isset( $entry[ $field['whatever'] ] )`  will still throw a notice. 

I _think_ we can rely on GF to keep the field array structure ( I know specifically the address field keeps it and uses `isHidden` if a field is disabled, but I'd want to check the others).

Please confirm you agree the risk is negligible, and I'll get to work updating the PR to use `??`. 😊

**Comment by kellenmace** [comment]
Sure thing 👍

If you've verified that GF always saves the `$field` array in the same format and we know those array keys will always be set, then I think `??` will work well. Otherwise, I think `! empty()` would be best:

```
'street'  => ! empty( $entry[ $field['inputs'][0]['id'] ] ) ? $entry[ $field['inputs'][0]['id'] ] : null;
```
^ That would suppress all PHP error reporting.

And the same would apply for the other field types, as well (unless a falsey value like `''` can be considered valid for any of them -- in that case, I would use `isset()` over `! empty()`).

**Comment by justlevine** [comment]
Switched to `isset()` / `??` as discussed.

**Pull request merged**
